Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Controllers/Weixin/TenPay/TenPayV3Controller.cs
/*----------------------------------------------------------------
    Copyright (C) 2022 Senparc
    
    文件名：TenPayV3Controller.cs
    文件功能描述：微信支付V3Controller
    
    
    创建标识：Senparc - 20150312
 
    修改标识：Senparc - 20150419
    修改描述：添加产品相关

    修改标识：Senparc - 20161203
    修改描述：调用新版Unifiedorder方法

    修改标识：Senparc - 20161204
    修改描述：调用新版Unifiedorder方法
----------------------------------------------------------------*/

/* 注意：TenPayV3Controller 是微信文档 V3 的示例，并非微信之后出来的 API V3，
 * 微信真正微信支付 API V3 的示例请见 TenPayApiV3Controller 
 */

//DPBMARK_FILE TenPay
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.Helpers;
using Senparc.CO2NET.Trace;
using Senparc.CO2NET.Utilities;
using Senparc.Weixin.Exceptions;
using Senparc.Weixin.Helpers;
using Senparc.Weixin.Sample.Net6.Models;
using Senparc.Weixin.TenPay.V3;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Xml.Linq;
using ZXing;
using ZXing.Common;
using TenPayOldV3 = Senparc.Weixin.TenPay.V3.TenPayV3;

//DPBMARK MP
using Senparc.Weixin.MP;
using Senparc.Weixin.MP.AdvancedAPIs;
using Senparc.Weixin.Sample.CommonService.TemplateMessage;
using Senparc.Weixin.Sample.Net6.Filters;
//DPBMARK_END


namespace Senparc.Weixin.Sample.Net6.Controllers
{
    /* 
     * 友情提示：微信支付正式上线之前，请进行沙箱测试！ 
     * 单元测试见：Senparc.Weixin.MP.Test/TenPayV3/TenPayV3Test.cs/GetSignKeyTest()
     */


    /// <summary>
    /// 根据官方的Webforms Demo改写，所以可以看到直接Response.Write()之类的用法，实际项目中不提倡这么做。
    /// </summary>
    public class TenPayV3Controller : BaseController
    {
        private static TenPayV3Info _tenPayV3Info;

        private static bool CheckValidationResult(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
        {
            if (errors == SslPolicyErrors.None)
                return true;
            return false;
        }

        public static TenPayV3Info TenPayV3Info
        {
            get
            {
                if (_tenPayV3Info == null)
                {
                    var key = TenPayHelper.GetRegisterKey(Config.SenparcWeixinSetting);

                    _tenPayV3Info =
                        TenPayV3InfoCollection.Data[key];
                }
                return _tenPayV3Info;
            }
        }

        private readonly IServiceProvider _serviceProvider;
        public TenPayV3Controller(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        /// <summary>
        /// 获取用户的OpenId
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int productId = 0, int hc = 0)
        {
            if (productId == 0 && hc == 0)
            {
                return RedirectToAction("ProductList");
            }

            var returnUrl = string.Format("https://sdk.weixin.senparc.com/TenPayV3/JsApi");
            var state = string.Format("{0}|{1}", productId, hc);
            string url = null;

            url = OAuthApi.GetAuthorizeUrl(TenPayV3Info.AppId, returnUrl, state, OAuthScope.snsapi_userinfo);//   -- DPBMARK MP DPBMARK_END

            if (url.IsNullOrEmpty())
            {
                throw new Exception("此功能需要使用微信公众号，但未获取到 OAuth URL，如果此项目为自动僧城项目，请确保已经引用“公众号”");
            }
            return Redirect(url);
        }

        public ActionResult BankCode()
        {
            return View();
        }

        //DPBMARK MP
        #region JsApi支付

        public ActionResult OAuthCallback(string code, string state, string returnUrl)
        {
            try
            {
                if (string.IsNullOrEmpty(code))
                {
                    return Content("您拒绝了授权！");
                }

                if (!state.Contains("|"))
                {
                    //这里的state其实是会暴露给客户端的，验证能力很弱，这里只是演示一下
                    //实际上可以存任何想传递的数据，比如用户ID
                    return Content("验证失败！请从正规途径进入！1001");
                }

                //通过，用code换取access_token
                var openIdResult = OAuthApi.GetAccessToken(TenPayV3Info.AppId, TenPayV3Info.AppSecret, code);
                if (openIdResult.errcode != ReturnCode.请求成功)
                {
                    return Content("错误：" + openIdResult.errmsg);
                }

                HttpContext.Session.SetString("OpenId", openIdResult.openid);//进行登录

                //也可以使用FormsAuthentication等其他方法记录登录信息，如：
                //FormsAuthentication.SetAuthCookie(openIdResult.openid,false);

                return Redirect(returnUrl);
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }
        }

        //需要OAuth登录
        [CustomOAuth(null, "/TenpayV3/OAuthCallback")]
        public ActionResult JsApi(int productId, int hc)
        {
            try
            {
                //获取产品信息
                var products = ProductModel.GetFakeProductList();
                var product = products.FirstOrDefault(z => z.Id == productId);
                if (product == null || product.GetHashCode() != hc)
                {
                    return Content("商品信息不存在，或非法进入！1002");
                }

                //var openId = User.Identity.Name;
                var openId = HttpContext.Session.GetString("OpenId");

                string sp_billno = Request.Query["order_no"];
                if (string.IsNullOrEmpty(sp_billno))
                {
                    //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                    sp_billno = string.Format("{0}{1}{2}", TenPayV3Info.MchId/*10位*/, SystemTime.Now.ToString("yyyyMMddHHmmss"),
                        TenPayV3Util.BuildRandomStr(6));

                    //注意：以上订单号仅作为演示使用，如果访问量比较大，建议增加订单流水号的去重检查。
                }
                else
                {
                    sp_billno = Request.Query["order_no"];
                }

                var timeStamp = TenPayV3Util.GetTimestamp();
                var nonceStr = TenPayV3Util.GetNoncestr();

                var body = product == null ? "test" : product.Name;
                var price = product == null ? 100 : (int)(product.Price * 100);//单位：分
                var xmlDataInfo = new TenPayV3UnifiedorderRequestData(TenPayV3Info.AppId, TenPayV3Info.MchId, body, sp_billno, price, HttpContext.UserHostAddress()?.ToString(), TenPayV3Info.TenPayV3Notify, TenPay.TenPayV3Type.JSAPI, openId, TenPayV3Info.Key, nonceStr);

                var result = TenPayOldV3.Unifiedorder(xmlDataInfo);//调用统一订单接口
                                                                   //JsSdkUiPackage jsPackage = new JsSdkUiPackage(TenPayV3Info.AppId, timeStamp, nonceStr,);
                var package = string.Format("prepay_id={0}", result.prepay_id);

                ViewData["product"] = product;

                ViewData["appId"] = TenPayV3Info.AppId;
                ViewData["timeStamp"] = timeStamp;
                ViewData["nonceStr"] = nonceStr;
                ViewData["package"] = package;
                ViewData["paySign"] = TenPayOldV3.GetJsPaySign(TenPayV3Info.AppId, timeStamp, nonceStr, package, TenPayV3Info.Key);

                //临时记录订单信息，留给退款申请接口测试使用
                HttpContext.Session.SetString("BillNo", sp_billno);
                HttpContext.Session.SetString("BillFee", price.ToString());

                return View();
            }
            catch (Exception ex)
            {
                var msg = ex.Message;
                msg += "<br>" + ex.StackTrace;
                msg += "<br>==Source==<br>" + ex.Source;

                if (ex.InnerException != null)
                {
                    msg += "<br>===InnerException===<br>" + ex.InnerException.Message;
                }
                return Content(msg);
            }
        }

        /// <summary>
        /// 原生支付 模式一
        /// </summary>
        /// <returns></returns>
        public ActionResult Native()
        {
            try
            {
                RequestHandler nativeHandler = new RequestHandler(null);
                string timeStamp = TenPayV3Util.GetTimestamp();
                string nonceStr = TenPayV3Util.GetNoncestr();

                //商品Id，用户自行定义
                string productId = SystemTime.Now.ToString("yyyyMMddHHmmss");

                nativeHandler.SetParameter("appid", TenPayV3Info.AppId);
                nativeHandler.SetParameter("mch_id", TenPayV3Info.MchId);
                nativeHandler.SetParameter("time_stamp", timeStamp);
                nativeHandler.SetParameter("nonce_str", nonceStr);
                nativeHandler.SetParameter("product_id", productId);
                string sign = nativeHandler.CreateMd5Sign("key", TenPayV3Info.Key);

                var url = TenPayOldV3.NativePay(TenPayV3Info.AppId, timeStamp, TenPayV3Info.MchId, nonceStr, productId, sign);

                BitMatrix bitMatrix;
                bitMatrix = new MultiFormatWriter().encode(url, BarcodeFormat.QR_CODE, 600, 600);
                var bw = new ZXing.BarcodeWriterPixelData();

                var pixelData = bw.Write(bitMatrix);
                var bitmap = new System.Drawing.Bitmap(pixelData.Width, pixelData.Height, System.Drawing.Imaging.PixelFormat.Format32bppRgb);

                var fileStream = new MemoryStream();

                var bitmapData = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, pixelData.Width, pixelData.Height), System.Drawing.Imaging.ImageLockMode.WriteOnly, System.Drawing.Imaging.PixelFormat.Format32bppRgb);
                try
                {
                    // we assume that the row stride of the bitmap is aligned to 4 byte multiplied by the width of the image   
                    System.Runtime.InteropServices.Marshal.Copy(pixelData.Pixels, 0, bitmapData.Scan0, pixelData.Pixels.Length);
                }
                finally
                {

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/H5Pay.cshtml
@using Senparc.Weixin.Sample.Net6.Models
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>公众号H5支付测试网页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }

        .product {
            font-size: 200%;
            color: #a5a5a5;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .WCPay {
            padding-top: 3%;
        }
    </style>
    <script>
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        $(function() {
            jQuery('a#getBrandWCPayRequest').click(function () {
                location.href = '@Html.Raw(ViewData["MWebUrl"])';
            });
        });

        if (jQuery) {
            jQuery(function () {

                var width = jQuery('body').width() * 0.87;
                jQuery('img').error(function () {
                    var self = jQuery(this);
                    var org = self.attr('data-original1');
                    self.attr("src", org);
                    self.error(function () {
                        auto_remove(this);
                    });
                });
                jQuery('img').each(function () {
                    var self = jQuery(this);
                    var w = self.css('width');
                    var h = self.css('height');
                    w = w.replace('px', '');
                    h = h.replace('px', '');
                    if (w <= width) {
                        return;
                    }
                    var new_w = width;
                    var new_h = Math.round(h * width / w);
                    self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                    self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                });
            });
        }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            @if (ViewData["product"] is ProductModel)
            {
                var product = (ProductModel)ViewData["product"];
                <div class="product">
                    您已选中产品：@product.Name<br />
                    单价：@product.Price.ToString("c")
                </div>
            }
            <h1 class="title">点击提交可体验H5微信支付</h1>
        </a>
        <p>注意：H5支付用于已经安装微信的手机客户端，使用微信外部浏览器网页内的支付。</p>
    </div>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/H5PaySuccess.cshtml
@using Senparc.Weixin.Sample.Net6.Models
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>公众号H5支付成功！</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }

        .product {
            font-size: 200%;
            color: #a5a5a5;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .WCPay {
            padding-top: 3%;
        }
    </style>
    <script>
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        $(function () {
            jQuery('a#getBrandWCPayRequest').click(function () {
                location.href = '@Url.Action("Refund", "TenPayV3")';
            });
        });

        if (jQuery) {
            jQuery(function () {

                var width = jQuery('body').width() * 0.87;
                jQuery('img').error(function () {
                    var self = jQuery(this);
                    var org = self.attr('data-original1');
                    self.attr("src", org);
                    self.error(function () {
                        auto_remove(this);
                    });
                });
                jQuery('img').each(function () {
                    var self = jQuery(this);
                    var w = self.css('width');
                    var h = self.css('height');
                    w = w.replace('px', '');
                    h = h.replace('px', '');
                    if (w <= width) {
                        return;
                    }
                    var new_w = width;
                    var new_h = Math.round(h * width / w);
                    self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                    self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                });
            });
        }
    </script>
</head>
<body>
    <div class="WCPay">
        <h1>支付成功！</h1>
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            @if (ViewData["product"] is ProductModel)
            {
                var product = (ProductModel)ViewData["product"];
                <div class="product">
                    您已选中产品：@product.Name<br />
                    单价：@product.Price.ToString("c")
                </div>
            }
            <h1 class="title">支付成功！进入退款流程测试。</h1>
        </a>
    </div>
    <div>注意：此页面只是展示一下返回结果（都会显示支付成功），实际使用过程中需要校验是否真的已经支付成功</div>

</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/Index.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>微信支付测试跳转页</title>

</head>
<body>
    <div>
    </div>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/JsApi.cshtml
@using Senparc.Weixin.Sample.Net6.Models
@*DPBMARK_FILE TenPay*@


@*提示：当前过程模拟的是订单支付过程（订单已经生成），不能对同一个订单号重复支付 *@

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>公众号jsapi支付测试网页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style>
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }

        .product {
            font-size: 200%;
            color: #a5a5a5;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .WCPay {
            padding-top: 3%;
        }
    </style>
    <script>
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        // 当微信内置浏览器完成内部初始化后会触发WeixinJSBridgeReady事件。
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            //公众号支付
            jQuery('a#getBrandWCPayRequest').click(function (e) {
                WeixinJSBridge.invoke('getBrandWCPayRequest', {
                    "appId": "@ViewData["appId"]", //公众号名称，由商户传入
                    "timeStamp": "@ViewData["timeStamp"]", //时间戳
                    "nonceStr": "@ViewData["nonceStr"]", //随机串
                    "package": "@Html.Raw(ViewData["package"])",//扩展包
                    "signType": "MD5", //微信签名方式:MD5
                    "paySign": "@ViewData["paySign"]" //微信签名
                }, function (res) {

                    //alert(JSON.stringify(res));

                    if (res.err_msg == "get_brand_wcpay_request:ok") {
                        if (confirm('支付成功！点击“确定”进入退款流程测试。')) {
                            location.href = '@Url.Action("Refund", "TenPayV3")';
                        }
                        //console.log(JSON.stringify(res));
                    }
                    // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
                    //因此微信团队建议，当收到ok返回时，向商户后台询问是否收到交易成功的通知，若收到通知，前端展示交易成功的界面；若此时未收到通知，商户后台主动调用查询订单接口，查询订单的当前状态，并反馈给前端展示相应的界面。
                });

            });

            WeixinJSBridge.log('yo~ ready.');

        }, false);
        if (jQuery) {
            jQuery(function () {

                var width = jQuery('body').width() * 0.87;
                jQuery('img').error(function () {
                    var self = jQuery(this);
                    var org = self.attr('data-original1');
                    self.attr("src", org);
                    self.error(function () {
                        auto_remove(this);
                    });
                });
                jQuery('img').each(function () {
                    var self = jQuery(this);
                    var w = self.css('width');
                    var h = self.css('height');
                    w = w.replace('px', '');
                    h = h.replace('px', '');
                    if (w <= width) {
                        return;
                    }
                    var new_w = width;
                    var new_h = Math.round(h * width / w);
                    self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                    self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                });
            });
        }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            @if (ViewData["product"] is ProductModel)
            {
                var product = (ProductModel)ViewData["product"];
                <div class="product">
                    您已选中产品：@product.Name<br />
                    单价：@product.Price.ToString("c")
                </div>
            }
            <h1 class="title">点击提交可体验微信支付</h1>
            <p>提示：支付成功后可退款，并体验退款流程</p>
        </a>
    </div>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/PayNotifyUrl.cshtml
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}

<html>
<head>
    <title>PayNotifyUrl</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/ProductItem.cshtml
@model Senparc.Weixin.Sample.Net6.Models.ProductModel
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>商品详情</title>
</head>
<body>
    <div>
        <h1>商品名称：@Model.Name</h1>
        <p>单价：@Model.Price.ToString("c")</p>
    </div>
    <hr />

    <h2>支付方式一：H5支付</h2>
    <p>注意：H5支付用于已经安装微信的手机客户端，使用微信外部浏览器网页内的支付。</p>
    <p>@Html.ActionLink("点击这里使用H5支付", "H5Pay", "TenPayV3", new { productId = Model.Id, hc = Model.GetHashCode() }, null)</p>
    <hr />

    <h2>支付方式二：“扫一扫”支付（JsApi）</h2>
    <p>
        使用微信“扫一扫”下方二维码完成支付：<br />
        <img src="@Url.Action("ProductPayCode",new{productId=Model.Id,hc=Model.GetHashCode()})" width="300" />
    </p>
    <p>提示：如果是在微信内部打开商品页面，则不会进入此页面，直接进入 JsApi 支付。</p>
    <hr />

</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/ProductList.cshtml
@model List<Senparc.Weixin.Sample.Net6.Models.ProductModel>
@*DPBMARK_FILE TenPay*@
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>产品列表</title>
    <style>
        ul#productList, ul#productList li {
            list-style: none;
            /*display: inline;*/
        }

            ul#productList li {
                border: 1px solid #008b8b;
                background: #c9ff94;
                padding: 6%;
                margin: 4%;
                overflow: hidden;
                float: left;
            }

                ul#productList li.br {
                    clear: left;
                }

                ul#productList li a {
                    text-decoration: none;
                    display: block;
                    overflow: hidden;
                    clear: both;
                }
    </style>
</head>
<body>
    <h2>微信支付 V2（Senparc.Weixin.TenPay.dll）</h2>

@if (Senparc.Weixin.BrowserUtility.BrowserUtility.SideInWeixinBrowser(this.Context))
{
    <div>提示：此网页在微信外部浏览器中打开可以体验“扫一扫支付”和“H5”支付</div>
}
else
{
    <div>提示：此页面在微信浏览器内打开可以体验微信JS-SDK微信支付</div>
}
<div>
    <ul id="productList">
        @for (int i = 0; i <= Model.Count - 1; i++)
        {
            var item = Model[i];
            <li class="@(i > 0 && i % 4 == 0 ? "br" : null)">
                <a href="@Url.Action("ProductItem", "TenPayV3", new {productId = item.Id, hc = item.GetHashCode()})">
                    <h2>@item.Name</h2>
                    <p>@item.Price.ToString("c")</p>
                    <p>点击购买</p>
                </a>
            </li>
        }
    </ul>
</div>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/Refund.cshtml
@*DPBMARK_FILE TenPay*@

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>退款结果页面</title>
</head>
<body>
    <h2>@ViewData["Message"]</h2>

    <p>&nbsp;</p>
    <p><a href="javascript:location.reload();">刷新状态</a>  |  @Html.ActionLink("返回支付首页", "ProductList")</p>
</body>
</html>

Samples/All/net6-mvc/Senparc.Weixin.Sample.Net6/Views/TenPayV3/View.cshtml
@*DPBMARK_FILE TenPay*@

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>微信支付退款演示</title>
</head>
<body>
    <h2>@ViewData["Message"]</h2>

    <p>&nbsp;</p>
    <p>@Html.ActionLink("返回支付产品列表", "Index")</p>
</body>
</html>